
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author iagop
 */
public class Contadortela extends javax.swing.JFrame {

    /**
     * Creates new form Contadortela
     */
    public Contadortela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sliderStart = new javax.swing.JSlider();
        sliderEnd = new javax.swing.JSlider();
        sliderSteps = new javax.swing.JSlider();
        lblStart = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        lblSteps = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listResult = new javax.swing.JList<>();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inicio");

        jLabel2.setText("Final");

        jLabel3.setText("Passos");

        sliderStart.setMaximum(30);
        sliderStart.setSnapToTicks(true);
        sliderStart.setValue(0);
        sliderStart.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStartStateChanged(evt);
            }
        });

        sliderEnd.setMaximum(30);
        sliderEnd.setSnapToTicks(true);
        sliderEnd.setValue(0);
        sliderEnd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderEndStateChanged(evt);
            }
        });

        sliderSteps.setMaximum(10);
        sliderSteps.setMinimum(1);
        sliderSteps.setSnapToTicks(true);
        sliderSteps.setValue(0);
        sliderSteps.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStepsStateChanged(evt);
            }
        });

        lblStart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStart.setForeground(new java.awt.Color(255, 0, 51));
        lblStart.setText("0");

        lblEnd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEnd.setForeground(new java.awt.Color(255, 0, 51));
        lblEnd.setText("0");

        lblSteps.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSteps.setForeground(new java.awt.Color(255, 0, 51));
        lblSteps.setText("1");

        listResult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(listResult);

        btnStart.setText("CONTAR");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderSteps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSteps))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStart))
                    .addComponent(sliderStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEnd))
                    .addComponent(sliderEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblStart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblEnd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblSteps))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStart)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderStartStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStartStateChanged
        // TODO add your handling code here:
        int start = sliderStart.getValue();
        lblStart.setText(String.valueOf(start));
    }//GEN-LAST:event_sliderStartStateChanged

    private void sliderEndStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderEndStateChanged
        // TODO add your handling code here:
        int end = sliderEnd.getValue();
        lblEnd.setText(String.valueOf(end));
    }//GEN-LAST:event_sliderEndStateChanged

    private void sliderStepsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStepsStateChanged
        // TODO add your handling code here:
        int steps = sliderSteps.getValue();
        lblSteps.setText(String.valueOf(steps));
    }//GEN-LAST:event_sliderStepsStateChanged

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        int start, end, steps;
        start = sliderStart.getValue();
        end = sliderEnd.getValue();
        steps = sliderSteps.getValue();
        boolean reverse = start > end;
        DefaultListModel lista = new DefaultListModel();
        DefaultListModel listaReverse = new DefaultListModel();

        System.out.println("reverse = " + reverse);
        if (reverse) {
            System.out.println("starting loop");
            for (int i = start; i >= end; i -= steps) {
                System.out.println("add " +i+ " to reverse list");
                listaReverse.addElement(i);
            }
        } else {
            for (int i = start; i <= end; i += steps) {
                lista.addElement(i);
            }
        }
        if (reverse) {
            listResult.setModel(listaReverse);
        } else {
            listResult.setModel(lista);
        }
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contadortela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contadortela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contadortela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contadortela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contadortela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblSteps;
    private javax.swing.JList<String> listResult;
    private javax.swing.JSlider sliderEnd;
    private javax.swing.JSlider sliderStart;
    private javax.swing.JSlider sliderSteps;
    // End of variables declaration//GEN-END:variables
}
